version: '3.8'

services:
  vue-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args: 
        STUDENT_NAME: "Weisly Bernard Wijaya"
        STUDENT_NIM: "00000053528"
    container_name: vue_app_container
    expose:
      - "5173"  # Expose the frontend port internally
    environment:
      - HOST=0.0.0.0
      - PORT=5173
    networks:
      - app_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args: 
        STUDENT_NAME: "Weisly Bernard Wijaya"
        STUDENT_NIM: "00000053528"
    container_name: backend_container
    expose:
      - "3000"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "80:80"  # Expose port 80 to the host
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Map your custom nginx configuration
    depends_on:
      - vue-app
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
